In [12]:
a = [1.0, 2.0, 1.0]
a[0]


1.0

In [13]:
a[2] = 3.0
a


[1.0, 2.0, 3.0]

In [15]:
import torch # <1>
a = torch.ones(3) # <2>
a
a[1]


tensor(1.)

In [17]:
float(a[1])
a[2] = 2.0
a


tensor([1., 1., 2.])

In [20]:
points = torch.zeros(6) # <1>
points[0] = 4.0
points[1] = 1.0
points[2] = 5.0
points[3] = 3.0
points[4] = 2.0
points[5] = 1.0
points = torch.tensor([4.0, 1.0, 5.0, 3.0, 2.0, 1.0])
points


tensor([4., 1., 5., 3., 2., 1.])

In [21]:
float(points[0]), float(points[1])
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points


tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [22]:
points.shape


torch.Size([3, 2])

In [23]:
points = torch.zeros(3, 2)
points


tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [24]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points


tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [25]:
points[0, 1]
points[0]


tensor([4., 1.])

In [26]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.storage()


 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [27]:
points_storage = points.storage()
points_storage[0]

4.0

In [30]:
points.storage()[1]
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_storage = points.storage()
points_storage[0] = 2.0
points

tensor([[2., 1.],
        [5., 3.],
        [2., 1.]])

In [32]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point.storage_offset()
second_point.size()
second_point.shape

torch.Size([2])

In [33]:
points.stride()


(2, 1)

In [35]:
second_point = points[1]
second_point.size()

torch.Size([2])

In [36]:
second_point.storage_offset()
second_point.stride()

(1,)

In [37]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1]
second_point[0] = 10.0
points


tensor([[ 4.,  1.],
        [10.,  3.],
        [ 2.,  1.]])

In [38]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
second_point = points[1].clone()
second_point[0] = 10.0
points


tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [39]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points


tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [40]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [41]:
id(points.storage()) == id(points_t.storage())
points.stride()

(2, 1)

In [42]:
points_t.stride()

(1, 2)

In [43]:
some_t = torch.ones(3, 4, 5)
transpose_t = some_t.transpose(0, 2)
some_t.shape

torch.Size([3, 4, 5])

In [44]:
transpose_t.shape

torch.Size([5, 4, 3])

In [45]:
some_t.stride()
transpose_t.stride()


(1, 5, 20)

In [47]:
points.is_contiguous()


True

In [48]:
points_t.is_contiguous()

False

In [49]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [50]:
points_t.storage()

 4.0
 1.0
 5.0
 3.0
 2.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [51]:
points_t.stride()


(1, 2)

In [52]:
points_t_cont = points_t.contiguous()
points_t_cont

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [53]:
points_t_cont.stride()

(3, 1)

In [54]:
points_t_cont.storage()

 4.0
 5.0
 2.0
 1.0
 3.0
 1.0
[torch.storage.TypedStorage(dtype=torch.float32, device=cpu) of size 6]

In [59]:
double_points = torch.ones(10, 2, dtype=torch.double)
short_points = torch.tensor([[1, 2], [3, 4]], dtype=torch.short)
short_points.dtype



torch.int16

In [60]:
double_points = torch.zeros(10, 2).double()
short_points = torch.ones(10, 2).short()

In [61]:
double_points = torch.zeros(10, 2).to(torch.double)
short_points = torch.ones(10, 2).to(dtype=torch.short)

In [62]:
points_64 = torch.rand(5, dtype=torch.double)  # <1>
points_short = points_64.to(torch.short)
points_64 * points_short

tensor([0., 0., 0., 0., 0.], dtype=torch.float64)

In [63]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [64]:
some_list = list(range(6))
some_list[:]     # <1>
some_list[1:4]   # <2>
some_list[1:]    # <3>
some_list[:4]    # <4>
some_list[:-1]   # <5>
some_list[1:4:2] # <6>


[1, 3]

In [65]:
points[1:]       # <1>
points[1:, :]    # <2>
points[1:, 0]    # <3>
points[None]     # <4>

tensor([[[4., 1.],
         [5., 3.],
         [2., 1.]]])

In [66]:
points = torch.ones(3, 4)
points_np = points.numpy()
points_np

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]], dtype=float32)

In [67]:
points = torch.from_numpy(points_np)


In [69]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [70]:
a = torch.ones(3, 2)
a_t = a.transpose(0, 1)

a.shape, a_t.shape

(torch.Size([3, 2]), torch.Size([2, 3]))

In [71]:
a = torch.ones(3, 2)

In [72]:
a.zero_()
a

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

In [75]:
import tensorflow as tf # Import TensorFlow

inputs = {
    'rows': [10, 20, 30],
    'cols': [1, 2, 3, 4],
}
tf.add(inputs['cols'], tf.expand_dims(inputs['rows'], 1)) # Use inputs dictionary to access 'rows' and 'cols'

<tf.Tensor: shape=(3, 4), dtype=int32, numpy=
array([[11, 12, 13, 14],
       [21, 22, 23, 24],
       [31, 32, 33, 34]], dtype=int32)>

In [77]:
inputs = {
    "boundaries": [10, 50, 100, 1000],
    "prices": [15, 3, 50, 90, 100, 1001],
}

tf.add(inputs['boundaries'], tf.expand_dims(inputs['prices'], 1)) # Use inputs dictionary to access 'rows' and 'cols'

<tf.Tensor: shape=(6, 4), dtype=int32, numpy=
array([[  25,   65,  115, 1015],
       [  13,   53,  103, 1003],
       [  60,  100,  150, 1050],
       [ 100,  140,  190, 1090],
       [ 110,  150,  200, 1100],
       [1011, 1051, 1101, 2001]], dtype=int32)>

In [81]:
import tensorflow as tf # Import TensorFlow

inputs = {
    'scores': [[0.7, 0.2, 0.1],
               [0.4, 0.5, 0.1],
               [0.4, 0.4, 0.2],
               [0.3, 0.4, 0.3],
               [0.0, 0.0, 1.0]],
}
tf.cast(tf.one_hot(tf.argmax(inputs['scores'], axis=1), 3), tf.int32) # Access the 'scores' tensor from the inputs dictionary

<tf.Tensor: shape=(5, 3), dtype=int32, numpy=
array([[1, 0, 0],
       [0, 1, 0],
       [1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int32)>

In [83]:
import tensorflow as tf

counts = [[0, 1, 0, 0],
          [0, 1, 1, 0],
          [1, 1, 1, 1]]
# Calculate the sum along axis 1 (columns) and keep the dimensions using keepdims=True
sum_counts = tf.reduce_sum(counts, axis=1, keepdims=True)
# Now, divide 'counts' by 'sum_counts', which have compatible shapes for broadcasting
normalized = tf.divide(counts, sum_counts)

In [84]:
inputs = {
    'counts': [[0, 1, 0, 0],
               [0, 1, 1, 0],
               [1, 1, 1, 1]],
}
tf.cast(tf.divide(counts, tf.expand_dims(tf.reduce_sum(counts, axis=1), axis=1)), tf.float32)


<tf.Tensor: shape=(3, 4), dtype=float32, numpy=
array([[0.  , 1.  , 0.  , 0.  ],
       [0.  , 0.5 , 0.5 , 0.  ],
       [0.25, 0.25, 0.25, 0.25]], dtype=float32)>